; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:wemos_d1_uno32]
platform = espressif32
board = wemos_d1_uno32
framework = arduino
upload_speed = 921600
extra_scripts = pre:load_env.py
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, colorize
board_build.partitions = min_spiffs.csv
build_flags =
	-DCORE_DEBUG_LEVEL=1
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=1
	-DCONFIG_ASYNC_TCP_USE_WDT=0
	-O2
	-DTF_LITE_STATIC_MEMORY
	-std=gnu++17
	-fno-exceptions
lib_deps =
	https://github.com/me-no-dev/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	mikalhart/TinyGPSPlus@^1.0.3
	tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
	# ── Fase 3: Firebase ────────────────────────────────────
	mobizt/Firebase Arduino Client Library for ESP8266 and ESP32@^4.4.14
